apiVersion: v1
kind: Service
metadata:
  name: kongsvc
  namespace: {{ .Release.Namespace }}
  labels:
    name: kongsvc
spec:
  type: {{ .Values.service.type }}
  externalTrafficPolicy: {{ .Values.service.externalTrafficPolicy }}
  ports:
  - port: 8000
    name: node8000
    protocol: TCP
    targetPort: 8000
    {{- if .Values.service.nodePort.node8000 }}
    nodePort: {{ .Values.service.nodePort.node8000 }}
    {{- end }}
  - port: 8001
    name: node8001   
    protocol: TCP
    targetPort: 8001
    {{- if .Values.service.nodePort.node8001 }}
    nodePort: {{ .Values.service.nodePort.node8001 }}
    {{- end }}
  selector:
    app: kong
